#!/usr/bin/env python3
"""Recalculate Tables 5.6 and 5.7 — Prefetch interaction analysis.

Reads the combined .dat files generated by embench_tex_sweep_combined.py for
specific benchmarks and cache-line counts, then computes:

Table 5.6 (tab:prefetch-raw):
    Raw cache_clock values for RV32IM/RV32IMC × prefetch/no-prefetch.

Table 5.7 (tab:prefetch-interaction):
    P_RV32IM   = (T_N - T_P) / T_N * 100   (prefetch benefit for RV32IM)
    P_RV32IMC  = (T_N - T_P) / T_N * 100   (prefetch benefit for RV32IMC)
    R_P        = P_RV32IMC / P_RV32IM       (relative effectiveness)

Where T_P = clock with prefetch, T_N = clock without prefetch.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path


def find_repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


@dataclass
class DatRow:
    cache_lines: int
    cache_bytes: int
    rv32im_p: int
    rv32imc_p: int
    rv32im_n: int
    rv32imc_n: int


@dataclass
class PrefetchPoint:
    benchmark: str
    interval: str
    point: int
    rv32im_p: int      # RV32IM with prefetch
    rv32im_n: int      # RV32IM without prefetch
    rv32imc_p: int     # RV32IMC with prefetch
    rv32imc_n: int     # RV32IMC without prefetch


@dataclass
class PrefetchResult:
    benchmark: str
    p_rv32im: float    # prefetch benefit % for RV32IM
    p_rv32imc: float   # prefetch benefit % for RV32IMC
    r_p: float         # ratio P_RV32IMC / P_RV32IM


def load_dat(path: Path) -> list[DatRow]:
    """Load a combined four-curve sweep generated by the combined script."""
    rows = []
    with path.open() as f:
        header = f.readline().split()
        required = [
            "cache_lines",
            "cache_bytes",
            "rv32im_prefetch",
            "rv32imc_prefetch",
            "rv32im_no_prefetch",
            "rv32imc_no_prefetch",
        ]
        if any(column not in header for column in required):
            raise ValueError(f"Unexpected columns in {path}: {' '.join(header)}")
        indexes = {column: header.index(column) for column in required}
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            rows.append(DatRow(
                cache_lines=int(parts[indexes["cache_lines"]]),
                cache_bytes=int(parts[indexes["cache_bytes"]]),
                rv32im_p=int(parts[indexes["rv32im_prefetch"]]),
                rv32imc_p=int(parts[indexes["rv32imc_prefetch"]]),
                rv32im_n=int(parts[indexes["rv32im_no_prefetch"]]),
                rv32imc_n=int(parts[indexes["rv32imc_no_prefetch"]]),
            ))
    return rows


def find_value_at_line(rows: list[DatRow], target_lines: int) -> DatRow | None:
    """Find the exact row for a given cache_lines value."""
    for row in rows:
        if row.cache_lines == target_lines:
            return row
    return None


def find_interval(rows: list[DatRow], target: int) -> str:
    """Describe the approximate plateau interval around the target point.

    Uses a simple heuristic: find the range where all 4 values change by <5%
    relative to the target point values.
    """
    target_row = find_value_at_line(rows, target)
    if target_row is None:
        return "?"

    threshold = 0.05
    ref_values = [
        target_row.rv32im_p,
        target_row.rv32imc_p,
        target_row.rv32im_n,
        target_row.rv32imc_n,
    ]
    stable_lines = []

    for row in rows:
        current = [row.rv32im_p, row.rv32imc_p, row.rv32im_n, row.rv32imc_n]
        if all(
            abs(c - r) / r < threshold if r != 0 else c == 0
            for c, r in zip(current, ref_values)
        ):
            stable_lines.append(row.cache_lines)

    if stable_lines:
        return f"{min(stable_lines)}--{max(stable_lines)}"
    return f"{target}"


def compute_prefetch_benefit(t_n: int, t_p: int) -> float:
    """Compute (T_N - T_P) / T_N * 100."""
    if t_n == 0:
        return 0.0
    return (t_n - t_p) / t_n * 100.0


# Default benchmark configurations matching Chapter 5
DEFAULT_CONFIGS = [
    # Explicit interior points of locally stable regions shared by all four curves.
    # PicoJPEG has no broad plateau in the measured sweep; 57 is the centre of
    # the local 54--60 region selected by the <5% heuristic in find_interval().
    {"name": "picojpeg",      "point": 57,  "interval": "54--60"},
    {"name": "doom",          "point": 48,  "interval": "36--54"},
    {"name": "nsichneu",      "point": 120, "interval": "3--255"},
    {"name": "statemate",     "point": 24,  "interval": "9--36"},
    {"name": "nettle_sha256", "point": 72,  "interval": "45--108"},
]


def main() -> None:
    ROOT = find_repo_root()

    parser = argparse.ArgumentParser(
        description="Recalculate Tables 5.6/5.7: prefetch interaction analysis."
    )
    parser.add_argument(
        "--data-dir", type=Path,
        default=ROOT / "data",
        help="Path containing *_icache_sweep_combined.dat files",
    )
    parser.add_argument("--latex", action="store_true", help="Output LaTeX tables")
    parser.add_argument("--csv", action="store_true", help="Output CSV format")

    args = parser.parse_args()

    data_dir = args.data_dir
    if not data_dir.is_dir():
        print(f"Error: Data directory not found: {data_dir}", file=sys.stderr)
        sys.exit(1)

    points: list[PrefetchPoint] = []
    results: list[PrefetchResult] = []

    print("=" * 80)
    print("TABLE 5.6: Raw cache_clock values (prefetch vs no-prefetch)")
    print("=" * 80)

    for cfg in DEFAULT_CONFIGS:
        name = cfg["name"]
        target_line = cfg["point"]
        display_name = name.replace("_", "-")

        dat_file = data_dir / f"{name}_icache_sweep_combined.dat"

        if not dat_file.is_file():
            print(f"  Warning: {dat_file} not found, skipping {name}", file=sys.stderr)
            continue

        rows = load_dat(dat_file)
        value = find_value_at_line(rows, target_line)

        if value is None:
            print(f"  Warning: no data at {target_line} lines in {dat_file}", file=sys.stderr)
            continue

        # Compute interval
        interval = find_interval(rows, target_line)
        # Override with known interval if available
        if "interval" in cfg:
            interval = cfg["interval"]

        point = PrefetchPoint(
            benchmark=display_name,
            interval=interval,
            point=target_line,
            rv32im_p=value.rv32im_p,
            rv32im_n=value.rv32im_n,
            rv32imc_p=value.rv32imc_p,
            rv32imc_n=value.rv32imc_n,
        )
        points.append(point)

        print(f"\n  {display_name} (point={target_line}, interval={interval}):")
        print(f"    RV32IM  with prefetch:    {value.rv32im_p:>12d}")
        print(f"    RV32IM  without prefetch: {value.rv32im_n:>12d}")
        print(f"    RV32IMC with prefetch:    {value.rv32imc_p:>12d}")
        print(f"    RV32IMC without prefetch: {value.rv32imc_n:>12d}")

        # Compute Table 5.7 values
        p_rv32im = compute_prefetch_benefit(value.rv32im_n, value.rv32im_p)
        p_rv32imc = compute_prefetch_benefit(value.rv32imc_n, value.rv32imc_p)
        r_p = p_rv32imc / p_rv32im if p_rv32im != 0 else float("inf")

        result = PrefetchResult(
            benchmark=display_name,
            p_rv32im=p_rv32im,
            p_rv32imc=p_rv32imc,
            r_p=r_p,
        )
        results.append(result)

        print(f"    P_RV32IM  = {p_rv32im:.2f}%")
        print(f"    P_RV32IMC = {p_rv32imc:.2f}%")
        print(f"    R_P       = {r_p:.2f}×")

    # Summary
    print("\n" + "=" * 80)
    print("TABLE 5.7: Prefetch benefit and interaction ratio")
    print("=" * 80)
    print(f"\n{'Benchmark':<20s} {'P_RV32IM':>10s} {'P_RV32IMC':>10s} {'R_P':>8s}")
    print("-" * 50)
    for r in results:
        print(f"{r.benchmark:<20s} {r.p_rv32im:>9.2f}% {r.p_rv32imc:>9.2f}% {r.r_p:>7.2f}×")

    if args.latex:
        print("\n\n--- LaTeX Table 5.6 (tab:prefetch-raw) ---")
        tex_lines = [
            r"\begin{table}[!ht]",
            r"\centering",
            r"\scriptsize",
            r"\resizebox{\textwidth}{!}{%",
            r"\begin{tabular}{lrrrrrr}",
            r"\hline",
            r"\textbf{Benchmark} & \textbf{Intervallo} & \textbf{Punto} &",
            r"\textbf{RV32IM P} & \textbf{RV32IM N} & \textbf{RV32IMC P} & \textbf{RV32IMC N} \\",
            r"\hline",
        ]
        for pt in points:
            bname = pt.benchmark.replace("_", r"\_").replace("-", r"-")
            tex_lines.append(
                rf"\texttt{{{bname}}}          & {pt.interval}  & {pt.point}  "
                rf"& {pt.rv32im_p}   & {pt.rv32im_n}   & {pt.rv32imc_p}   & {pt.rv32imc_n} \\"
            )
        tex_lines.extend([
            r"\hline",
            r"\end{tabular}",
            r"}",
            r"\caption{Quattro misure di \texttt{cache\_clock} per ciascun benchmark.}",
            r"\label{tab:prefetch-raw}",
            r"\end{table}",
        ])
        print("\n".join(tex_lines))

        print("\n\n--- LaTeX Table 5.7 (tab:prefetch-interaction) ---")
        tex_lines2 = [
            r"\begin{table}[!ht]",
            r"\centering",
            r"\small",
            r"\begin{tabular}{lrrr}",
            r"\hline",
            r"\textbf{Benchmark} & \textbf{$P_{\mathrm{RV32IM}}$} &",
            r"\textbf{$P_{\mathrm{RV32IMC}}$} & \textbf{$R_P$} \\",
            r"\hline",
        ]
        for r in results:
            bname = r.benchmark.replace("_", r"\_").replace("-", r"-")
            tex_lines2.append(
                rf"\texttt{{{bname}}}          & {r.p_rv32im:.2f}\%  "
                rf"& {r.p_rv32imc:.2f}\%  & \({r.r_p:.2f}\times\) \\"
            )
        tex_lines2.extend([
            r"\hline",
            r"\end{tabular}",
            r"\caption{Beneficio percentuale del prefetch e rapporto tra il beneficio osservato con RV32IMC e quello osservato con RV32IM.}",
            r"\label{tab:prefetch-interaction}",
            r"\end{table}",
        ])
        print("\n".join(tex_lines2))

    if args.csv:
        print("\n--- CSV Table 5.6 ---")
        print("benchmark,interval,point,rv32im_p,rv32im_n,rv32imc_p,rv32imc_n")
        for pt in points:
            print(f"{pt.benchmark},{pt.interval},{pt.point},{pt.rv32im_p},{pt.rv32im_n},{pt.rv32imc_p},{pt.rv32imc_n}")

        print("\n--- CSV Table 5.7 ---")
        print("benchmark,p_rv32im,p_rv32imc,r_p")
        for r in results:
            print(f"{r.benchmark},{r.p_rv32im:.2f},{r.p_rv32imc:.2f},{r.r_p:.2f}")


if __name__ == "__main__":
    main()
